spring.application.name=//

spring.data.mongodb.uri=//

spring.data.mongodb.database=//

server.port=//

razorpay.key=//

razorpay.secret=//

app.jwt.secret=//
app.jwt.expiration-ms=//
>>>>>>> 29a6dd77aea49da4183b960d8782e04f48090b60

app.admin.seed.email=//
app.admin.seed.password=//
app.admin.seed.name=//
